// Code generated by "stringer -type=EndGameMsg -linecomment"; DO NOT EDIT.

package breach

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Quit-0]
	_ = x[Continue-1]
	_ = x[Restart-2]
}

const _EndGameMsg_name = "QuitContinueRestart"

var _EndGameMsg_index = [...]uint8{0, 4, 12, 19}

func (i EndGameMsg) String() string {
	if i < 0 || i >= EndGameMsg(len(_EndGameMsg_index)-1) {
		return "EndGameMsg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EndGameMsg_name[_EndGameMsg_index[i]:_EndGameMsg_index[i+1]]
}
