// Code generated by "stringer -type=Symbol -linecomment"; DO NOT EDIT.

package breach

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[X55-0]
	_ = x[XBD-1]
	_ = x[XE9-2]
	_ = x[X7A-3]
	_ = x[X1C-4]
	_ = x[delim_end-5]
	_ = x[XXX-6]
}

const _Symbol_name = "55BDE97A1Cdelim_endXX"

var _Symbol_index = [...]uint8{0, 2, 4, 6, 8, 10, 19, 21}

func (i Symbol) String() string {
	if i < 0 || i >= Symbol(len(_Symbol_index)-1) {
		return "Symbol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Symbol_name[_Symbol_index[i]:_Symbol_index[i+1]]
}
